/world_spawner/enable_asphalt: true
/world_spawner/plane_sizes: [50, 55]
/world_spawner/plane_pose: [-9.5, -57] 
/world_spawner/steerbot_road_width: 4
/world_spawner/random_type_spawn: [true, false]
/world_spawner/random_cars_to_spawn: [10, 15]
/world_spawner/random_rectangle_area: [15.0, 15.0, 40, 40]
/world_spawner/boxes_to_spawn: ['C']
/world_spawner/boxes_x_pose: [10]
/world_spawner/boxes_y_pose: [-35]
/world_spawner/boxes_rows_number: [8]

