/world_spawner/enable_asphalt: false
/world_spawner/plane_sizes: [300, 300] 
/world_spawner/steerbot_road_width: 4
/world_spawner/random_type_spawn: [true, false]
/world_spawner/random_cars_to_spawn: [10, 15]
/world_spawner/random_rectangle_area: [15.0, 15.0, 40, 40]
/world_spawner/boxes_to_spawn: ['C', 'D']
/world_spawner/boxes_x_pose: [50, -40]
/world_spawner/boxes_y_pose: [40, -50]
/world_spawner/boxes_rows_number: [5, 10]



